server:
  address: "0.0.0.0"
  port: 8080
  db_path: "./database"
  tls:
    cert_file: ""
    key_file: ""
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  rate_limit:
    rps: 100_000
    burst: 200_000
  ip_whitelist:
    - "127.0.0.1"
  api_keys:
    backend: ["sk_example"]
    frontend: ["pk_example"]
    admin: ["admin_example"]

logging:
  level: "info"

retention:
  enabled: false
  cron: "0 2 * * *"
  period: "24h"
  batch_size: 1000
  batch_sleep_ms: 0
  dry_run: false
  paused: false
  min_period: "1h"
  lock_ttl: 300s

ingest:
  intake:
    queue_capacity: 500_000
    shutdown_poll_interval: 5ms
    wal:
      enabled: false
      segment_size: 20MB
    recovery:
      enabled: true
      wal_enabled: false
      temp_idx_enabled: false
  compute:
    worker_count: 64
    buffer_capacity: 100_000
  apply:
     batch_count: 1_000
     batch_timeout: 1s
     fsync_after_batch: true

telemetry:
  sample_rate: 0.001
  slow_threshold: 200ms
  buffer_size: 60MB
  file_max_size: 40MB
  flush_interval: 2s
  queue_capacity: 2048

sensor:
  monitor:
    poll_interval: 60s
    disk_high_pct: 80
    # disk_low_pct: 60
    mem_high_pct: 80
    recovery_window: 5s

encryption:
  enabled: false
  fields: []
  kms:
    mode: "embedded"
    endpoint: "127.0.0.1:6820"
    data_dir: "./kms-data"
    binary: "/usr/local/bin/progressdb-kms"
    master_key_file: ""
    master_key_hex: ""