version: 2

project_name: progressdb

builds:
  - id: progressdb
    dir: ./service
    main: ./cmd/progressdb
    binary: progressdb
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ trimprefix .Tag "service-" }} -X main.commit={{ .Commit }} -X main.buildDate={{ .Date }}
  - id: prgkms
    dir: ./kms
    main: ./cmd/prgkms
    binary: prgkms
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ trimprefix .Tag "service-" }} -X main.commit={{ .Commit }} -X main.buildDate={{ .Date }}

  # single server build includes both embedded and external KMS implementations

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - progressdb
    files:
      - LICENSE.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: ProgressDB   # 👈 replace
    name: progressdb              # 👈 repo name
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ trimprefix .Tag "service-" }}"
  header: |
    ## ProgressDB {{ trimprefix .Tag "service-" }}
  footer: |
    Docker Images:
    - docker.io/progressdb/progressdb:{{.Tag}}
    - ghcr.io/ProgressDB/progressdb:{{.Tag}}

changelog:
  use: github   # or "git"
  # Prefer GitHub username when available so changelog lines tag users (e.g. @octocat).
  # Fall back to author name or email when username mapping is not available.
  format: "{{.Message}} (by {{- if .AuthorUsername -}}@{{.AuthorUsername}}{{- else if .AuthorName -}}{{.AuthorName}}{{- else -}}{{.AuthorEmail}}{{- end -}})"
  filters:
    exclude:
      - "^docs:"   # don’t show docs commits
      - "^test:"   # don’t show test commits
  groups:
    - title: Features
      regexp: '^.*feat.*$'
      order: 0
    - title: Bug fixes
      regexp: '^.*fix.*$'
      order: 1
    - title: Others
      order: 999

dockers:
  - id: dockerhub_amd64
    image_templates:
      - "docker.io/progressdb/progressdb:{{ .Tag }}-amd64"
      - "docker.io/progressdb/progressdb:{{ trimprefix .Tag "service-" }}-amd64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    ids:
      - progressdb

  - id: dockerhub_kmsd_amd64
    image_templates:
      - "docker.io/progressdb/prgkms:{{ .Tag }}-amd64"
      - "docker.io/progressdb/prgkms:{{ trimprefix .Tag "service-" }}-amd64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    ids:
      - prgkms

  - id: dockerhub_arm64
    image_templates:
      - "docker.io/progressdb/progressdb:{{ .Tag }}-arm64"
      - "docker.io/progressdb/progressdb:{{ trimprefix .Tag "service-" }}-arm64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    ids:
      - progressdb

  - id: dockerhub_kmsd_arm64
    image_templates:
      - "docker.io/progressdb/prgkms:{{ .Tag }}-arm64"
      - "docker.io/progressdb/prgkms:{{ trimprefix .Tag "service-" }}-arm64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    ids:
      - prgkms

  - id: ghcr_amd64
    image_templates:
      - "ghcr.io/ProgressDB/progressdb:{{ .Tag }}-amd64"
      - "ghcr.io/ProgressDB/progressdb:{{ trimprefix .Tag "service-" }}-amd64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    ids:
      - progressdb

  - id: ghcr_kmsd_amd64
    image_templates:
      - "ghcr.io/ProgressDB/prgkms:{{ .Tag }}-amd64"
      - "ghcr.io/ProgressDB/prgkms:{{ trimprefix .Tag "service-" }}-amd64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    ids:
      - prgkms

  - id: ghcr_arm64
    image_templates:
      - "ghcr.io/ProgressDB/progressdb:{{ .Tag }}-arm64"
      - "ghcr.io/ProgressDB/progressdb:{{ trimprefix .Tag "service-" }}-arm64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    ids:
      - progressdb

  - id: ghcr_kmsd_arm64
    image_templates:
      - "ghcr.io/ProgressDB/prgkms:{{ .Tag }}-arm64"
      - "ghcr.io/ProgressDB/prgkms:{{ trimprefix .Tag "service-" }}-arm64"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    ids:
      - prgkms

docker_manifests:
  - name_template: "docker.io/progressdb/progressdb:{{ .Tag }}"
    image_templates:
      - "docker.io/progressdb/progressdb:{{ .Tag }}-amd64"
      - "docker.io/progressdb/progressdb:{{ .Tag }}-arm64"
  - name_template: "docker.io/progressdb/progressdb:{{ .Version }}"
    image_templates:
      - "docker.io/progressdb/progressdb:{{ .Version }}-amd64"
      - "docker.io/progressdb/progressdb:{{ .Version }}-arm64"

  - name_template: "docker.io/progressdb/prgkms:{{ .Tag }}"
    image_templates:
      - "docker.io/progressdb/prgkms:{{ .Tag }}-amd64"
      - "docker.io/progressdb/prgkms:{{ .Tag }}-arm64"
  - name_template: "docker.io/progressdb/prgkms:{{ .Version }}"
    image_templates:
      - "docker.io/progressdb/prgkms:{{ .Version }}-amd64"
      - "docker.io/progressdb/prgkms:{{ .Version }}-arm64"

  - name_template: "ghcr.io/ProgressDB/progressdb:{{ .Tag }}"
    image_templates:
      - "ghcr.io/ProgressDB/progressdb:{{ .Tag }}-amd64"
      - "ghcr.io/ProgressDB/progressdb:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/ProgressDB/progressdb:{{ .Version }}"
    image_templates:
      - "ghcr.io/ProgressDB/progressdb:{{ .Version }}-amd64"
      - "ghcr.io/ProgressDB/progressdb:{{ .Version }}-arm64"

  - name_template: "ghcr.io/ProgressDB/prgkms:{{ .Tag }}"
    image_templates:
      - "ghcr.io/ProgressDB/prgkms:{{ .Tag }}-amd64"
      - "ghcr.io/ProgressDB/prgkms:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/ProgressDB/prgkms:{{ .Version }}"
    image_templates:
      - "ghcr.io/ProgressDB/prgkms:{{ .Version }}-amd64"
      - "ghcr.io/ProgressDB/prgkms:{{ .Version }}-arm64"
