server:
  # Server listen address and TLS settings
  address: "0.0.0.0"
  port: 8080
  db_path: "./data/progressdb"
  tls:
    cert_file: ""
    key_file: ""

security:
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  rate_limit:
    rps: 10
    burst: 20
  ip_whitelist:
    - "127.0.0.1"
  api_keys:
    backend: ["sk_example"]
    frontend: ["pk_example"]
    admin: ["admin_example"]
  encryption:
    use: false
    fields: []
  kms:
    mode: "embedded" # or external
    endpoint: "127.0.0.1:6820" # host:port for HTTP (e.g. 127.0.0.1:6820) or full URL
    data_dir: "./kms-data"
    binary: "/usr/local/bin/progressdb-kms"
    master_key_file: ""
    master_key_hex: ""

logging:
  level: "info"
